name: Drupal CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, pdo, pdo_mysql, xml, ctype, json
          tools: composer

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Validate Composer
        run: composer validate --strict

      - name: Check Drupal Coding Standards
        run: |
          composer require --dev drupal/coder
          ./vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
          ./vendor/bin/phpcs -p --standard=Drupal,DrupalPractice --extensions=php,module,inc,install,test,profile,theme,info,module src/
